# Site settings
title: Khaki's Story
email: jiaqi228@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Geek face of Khaki can be found here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://khaki.github.io" # the base hostname & protocol for your site
twitter_username: 7jii
github_username:  Khaki

# Build settings
markdown: kramdown
